### ISSUE TITLE
League of Legends Patch 6.4

### ISSUE THREAD

**Issue by ClearCarbon** [multiplay/lancache#1]
Starting with patch 6.4 I have received the message "Unspecified error occurred. Please check logs for more information" when attempting to patch LoL with LANcache.

Removing the line 'address=/l3cdn.riotgames.com/192.168.1.216' from dnsmasq allows me to patch, but I'd rather keep LAN Cache working for LoL as I'm running a 24 person LAN on 2 ADSL lines.

Looking at the patcher logs there is an error that seems to stand out.

failure_identifier: ["E:\/jenkins\/workspace\/rads-code-win-release\/code\/Solutions\/RiotRADS\/Source\/RADS\/LoLPatcherLib\/UpdateWorker.cpp|399" (REMOVED - appeared to be a long array of file paths from Riots CI Server - left the first one for reference), for file:'\/releases\/live\/projects\/lol_air_client\/releases\/releaselisting'."]

Running curl l3cdn.riotgames.com/releases/live/projects/lol_air_client/releases/releaselisting appears to return a list of releases in the format 0.0.x.x (starting at 0.0.0.1 and ending at 0.0.1.188). This is returned by curl whether I have the dns redirection in my dnsmasq config or not.

I'm running lancache inside a jail on FreeNAS.

**Comment by bntjah** [comment]
Have a look over @ [Riot CDN is now served over HTTPS #8](https://github.com/ti-mo/ansible-lanparty/issues/8)

**Comment by ClearCarbon** [comment]
@bntjah thanks for the link, looks like this is up to riot to fix so I'll close the issue here.
