### ISSUE TITLE
Install guide walk through. 

### ISSUE THREAD

**Issue by nexusofdoom** [multiplay/lancache#10]
after installing freebsd 
what is the steps to install this ? 

thanks

**Comment by nexusofdoom** [comment]
install freebsd 10.x

pkg install git
pkg install ntp

 ntpdate -v -b in.pool.ntp.org

 git clone https://github.com/multiplay/lancache.git

how to download compile  and install nginx can we use the current version ?

**Comment by nexusofdoom** [comment]
install freebsd 10.x

pkg install git
pkg install ntp
pkg install sudo 

#Therefore, one way to grant a normal user with superuser privileges is to add the #user to the wheel group. To add a user to the wheel group, use this pw groupmod #command (replace the highlighted username):

#sammy would be your username 
#run from root user  
pw groupmod wheel -m "sammy"

#after that the su root command should work.
su root 

 ntpdate -v -b in.pool.ntp.org

 git clone https://github.com/multiplay/lancache.git

how to download compile  and install nginx can we use the current version ? 

#how to apply this patch ? https://github.com/multiplay/nginx-range-cache.git
git clone https://github.com/multiplay/nginx-range-cache.git
## example 
Install nginx

  curl -o nginx-1.10.0.tar.gz   http://nginx.org/download/nginx-1.10.0.tar.gz 
  tar xvfz nginx-1.10.0.tar.gz 

#get patch files command ?
#where does the patch file go ?
   
 cd ngnix-1.10.0

patch -p1 < ../nginx-range-cache/range_filter.patch

   ./configure 
   
#--with-range_cache_size --with-http_ssl_module --with-http_slice_module --#with-file-aio --with-threads

 make

 make install

**Comment by stevenh** [comment]
If you would like to create a walk through guide perhaps a [wiki page](https://github.com/multiplay/lancache/wiki) would be good

**Comment by nexusofdoom** [comment]
sounds good 

at this point I am stuck at what I need to pass to ./configure   --- for nginx options 

so far it looks like i need 
ngx_http_proxy_module
ngx_http_realip_module

what about the range patch how do I pass that with config after the patch is applied..

thanks

**Comment by stevenh** [comment]
If you're using FreeBSD I can look at adding a ports patch to this repo if that would help?
With that its just a matter of:
```sh
make config # select range cache option
make install
```

**Comment by nexusofdoom** [comment]
I am running
FreeBSD-10.3-RELEASE-amd64-dvd1.iso

**Comment by nexusofdoom** [comment]
the error I have
./configure: error: invalid option "--modules-path=/usr/local/libexec/nginx"




*this is what I have so far *

install freebsd 10.x

pkg install git
pkg install ntp
pkg install sudo
pkg install nano

#Therefore, one way to grant a normal user with superuser privileges is to
add the #user to the wheel group. To add a user to the wheel group, use
this pw groupmod #command (replace the highlighted username):

#sammy would be your username
#run from root user
pw groupmod wheel -m "sammy"

#after that the su root command should work.
su root

ntpdate -v -b in.pool.ntp.org

git clone https://github.com/multiplay/lancache.git

how to download compile and install nginx can we use the current version ?

#how to apply this patch ?
https://github.com/multiplay/nginx-range-cache.git
git clone https://github.com/multiplay/nginx-range-cache.git
## example
Install nginx

curl -o nginx-1.6.0.tar.gz http://nginx.org/download/nginx-1.6.0.tar.gz
tar xvfz nginx-1.6.0.tar.gz

#curl -o nginx-1.10.0.tar.gz http://nginx.org/download/nginx-1.10.0.tar.gz
#tar xvfz nginx-1.10.0.tar.gz

#get patch files command ?
#where does the patch file go ?

cd ngnix-1.10.0

patch -p1 < ../nginx-range-cache/range_filter.patch

# ./configure what options?
./configure --prefix=/usr/local/etc/nginx --with-cc-opt='-I
/usr/local/include' --with-ld-opt='-L /usr/local/lib'
--conf-path=/usr/local/etc/nginx/nginx.conf
--sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid
--error-log-path=/var/log/nginx/error.log --user=www --group=www
--modules-path=/usr/local/libexec/nginx --with-file-aio
--http-client-body-temp-path=/var/tmp/nginx/client_body_temp
--http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp
--http-proxy-temp-path=/var/tmp/nginx/proxy_temp
--http-scgi-temp-path=/var/tmp/nginx/scgi_temp
--http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp
--http-log-path=/var/log/nginx/access.log
--add-module=/usr/portbuild/www/nginx/work/ngx_cache_purge-2.3
--with-http_flv_module --with-http_geoip_module=dynamic
--with-http_gzip_static_module --with-http_image_filter_module=dynamic
--with-http_mp4_module
--add-module=/usr/portbuild/www/nginx/work/nginx-range-cache-0.2
--with-http_realip_module --with-http_slice_module
--with-http_stub_status_module --with-pcre --with-http_v2_module
--with-stream=dynamic --with-stream_ssl_module
--with-stream_ssl_preread_module --with-http_ssl_module

#--with-range_cache_size --with-http_ssl_module --with-http_slice_module
--#with-file-aio --with-threads

make

make install

#install location /usr/local/nginx/conf
#need to move files from lancache to this folder /usr/local/nginx/conf

#cd into the lancache folder
cp -rvf * /usr/local/nginx/conf/
cp -rvf *.* /usr/local/nginx/conf/


#DNS

#need to edit and add
nano /etc/hosts

#need to add your ip x.x.x.x example 192.168.1.2

x.x.x.x lancache-steam
x.x.x.x lancache-riot
x.x.x.x lancache-blizzard

x.x.x.x lancache-hirez

x.x.x.x lancache-origin

x.x.x.x lancache-sony

**Comment by stevenh** [comment]
Try the following patch.
It should apply cleanly to a the standard freebsd nginx port
[freebsd-nginx-port.zip](https://github.com/multiplay/lancache/files/1305022/freebsd-nginx-port.zip)

**Comment by nexusofdoom** [comment]
do you have a example how to apply this?

thanks

**Comment by stevenh** [comment]
Something along the lines of:
```sh
cd /usr/ports/www/nginx/
unzip freebsd-nginx-port.patch.zip
patch < freebsd-nginx-port.patch
```

**Comment by nexusofdoom** [comment]
Then run pgk install ngix ?

**Comment by nexusofdoom** [comment]
ok after I did the patch I ran

pkg install nginx

this is what I got

Proceed with this action? [y/N]: y
[1/1] Fetching nginx-1.12.1,2.txz: 100%  386 KiB 395.2kB/s    00:01
Checking integrity... done (0 conflicting)
[1/1] Installing nginx-1.12.1,2...
===> Creating groups.
Using existing group 'www'.
===> Creating users
Using existing user 'www'.
Extracting nginx-1.12.1,2: 100%
Message from nginx-1.12.1,2:
===================================================================
Recent version of the NGINX introduces dynamic modules support.  In
FreeBSD ports tree this feature was enabled by default with the DSO
knob.  Several vendor's and third-party modules have been converted
to dynamic modules.  Unset the DSO knob builds an NGINX without
dynamic modules support.

To load a module at runtime, include the new `load_module'
directive in the main context, specifying the path to the shared
object file for the module, enclosed in quotation marks.  When you
reload the configuration or restart NGINX, the module is loaded in.
It is possible to specify a path relative to the source directory,
or a full path, please see
https://www.nginx.com/blog/dynamic-modules-nginx-1-9-11/ and
http://nginx.org/en/docs/ngx_core_module.html#load_module for
details.

Default path for the NGINX dynamic modules is

/usr/local/libexec/nginx.
===================================================================


===>   NOTICE:

The nginx port currently does not have a maintainer. As a result, it is
more likely to have unresolved issues, not be up-to-date, or even be
removed in
the future. To volunteer to maintain this port, please create an issue at:

https://bugs.freebsd.org/bugzilla

More information about port maintainership is available at:

https://www.freebsd.org/doc/en/articles/contributing/ports-contributing.html#maintain-port



<http://www.discoverpc.net>
Travus Elm - Support Specialist
travus@discoverpc.net discoverpc.NET <http://discoverpc.net/>, 1402 Tower
Ave., Superior, WI 54880
Local: (715) 398-6767 ::: Toll-free: (800) 721-1350
Mobile: (218) 260-1940 ::: Fax: (866) 704-3660
*Follow or like us on **Google+*
<https://plus.google.com/111445774308955992766/about?gl=us&hl=en>*, **Facebook
<http://www.facebook.com/pages/discoverpcNET-Computer-Solutions-Center/35471145348>,
**LinkedIn
<https://www.linkedin.com/in/travus-elm-73842268?trk=nav_responsive_tab_profile>*

PRIVILEGED AND CONFIDENTIAL COMMUNICATION This e-mail transmission, and any
documents, files or previous e-mail messages attached to it, may contain
confidential information that is legally privileged. If you are not the
intended recipient or a person responsible for delivering it to the
intended recipient, you are hereby notified that any disclosure, copying,
distribution or use of any of the information contained in or attached to
this transmission is STRICTLY PROHIBITED. If you have received this
transmission in error, please: (1) immediately notify me by reply e-mail,
or by collect telephone call; and (2) destroy the original transmission and
its attachments without reading or saving in any manner
.

**Comment by nexusofdoom** [comment]
ok this is what i get when i start nginx after appying the zip patch

note only using Microsoft caching but i am still getting the unknown
directive "range_cache_size"

 /usr/local/etc/rc.d/nginx onestart
Performing sanity check on nginx configuration:
nginx: [emerg] unknown directive "range_cache_size" in
/usr/local/etc/nginx/lancache/node-microsoft:18
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
Starting nginx.



<http://www.discoverpc.net>
Travus Elm - Support Specialist
travus@discoverpc.net discoverpc.NET <http://discoverpc.net/>, 1402 Tower
Ave., Superior, WI 54880
Local: (715) 398-6767 ::: Toll-free: (800) 721-1350
Mobile: (218) 260-1940 ::: Fax: (866) 704-3660
*Follow or like us on **Google+*
<https://plus.google.com/111445774308955992766/about?gl=us&hl=en>*, **Facebook
<http://www.facebook.com/pages/discoverpcNET-Computer-Solutions-Center/35471145348>,
**LinkedIn
<https://www.linkedin.com/in/travus-elm-73842268?trk=nav_responsive_tab_profile>*

PRIVILEGED AND CONFIDENTIAL COMMUNICATION This e-mail transmission, and any
documents, files or previous e-mail messages attached to it, may contain
confidential information that is legally privileged. If you are not the
intended recipient or a person responsible for delivering it to the
intended recipient, you are hereby notified that any disclosure, copying,
distribution or use of any of the information contained in or attached to
this transmission is STRICTLY PROHIBITED. If you have received this
transmission in error, please: (1) immediately notify me by reply e-mail,
or by collect telephone call; and (2) destroy the original transmission and
its attachments without reading or saving in any manner
.

**Comment by nexusofdoom** [comment]
so going back to testing with using source
./configure --with-file-aio
--http-client-body-temp-path=/var/tmp/nginx/client_body_temp
--http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp
--http-proxy-temp-path=/var/tmp/nginx/proxy_temp
--http-scgi-temp-path=/var/tmp/nginx/scgi_temp
--http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp
--http-log-path=/var/log/nginx/access.log --with-http_flv_module
--with-http_gzip_static_module --with-http_mp4_module
--add-module=/usr/portbuild/www/nginx/work/nginx-range-cache-0.2
--with-http_realip_module --with-http_slice_module
--with-http_stub_status_module --with-pcre --with-http_v2_module
--with-stream=dynamic --with-stream_ssl_module --with-http_ssl_module


issues with purge module
and  this one
 --add-module=/usr/portbuild/www/nginx/work/nginx-range-cache-0.2






<http://www.discoverpc.net>
Travus Elm - Support Specialist
travus@discoverpc.net discoverpc.NET <http://discoverpc.net/>, 1402 Tower
Ave., Superior, WI 54880
Local: (715) 398-6767 ::: Toll-free: (800) 721-1350
Mobile: (218) 260-1940 ::: Fax: (866) 704-3660
*Follow or like us on **Google+*
<https://plus.google.com/111445774308955992766/about?gl=us&hl=en>*, **Facebook
<http://www.facebook.com/pages/discoverpcNET-Computer-Solutions-Center/35471145348>,
**LinkedIn
<https://www.linkedin.com/in/travus-elm-73842268?trk=nav_responsive_tab_profile>*

PRIVILEGED AND CONFIDENTIAL COMMUNICATION This e-mail transmission, and any
documents, files or previous e-mail messages attached to it, may contain
confidential information that is legally privileged. If you are not the
intended recipient or a person responsible for delivering it to the
intended recipient, you are hereby notified that any disclosure, copying,
distribution or use of any of the information contained in or attached to
this transmission is STRICTLY PROHIBITED. If you have received this
transmission in error, please: (1) immediately notify me by reply e-mail,
or by collect telephone call; and (2) destroy the original transmission and
its attachments without reading or saving in any manner
.

**Comment by nexusofdoom** [comment]
1. 12:17
   <https://matrix.to/#/!jBrKEBUjUHyYUnIDdA:fatbelly.space/$15054958301663WuetD:fatbelly.space>maybe
   out of date ports tree?
   2.
   12:17
   <https://matrix.to/#/!jBrKEBUjUHyYUnIDdA:fatbelly.space/$15054958611664kXsAt:fatbelly.space>the
   patch it retrieved was a different size than what was expected by the port



<http://www.discoverpc.net>
Travus Elm - Support Specialist
travus@discoverpc.net discoverpc.NET <http://discoverpc.net/>, 1402 Tower
Ave., Superior, WI 54880
Local: (715) 398-6767 ::: Toll-free: (800) 721-1350
Mobile: (218) 260-1940 ::: Fax: (866) 704-3660
*Follow or like us on **Google+*
<https://plus.google.com/111445774308955992766/about?gl=us&hl=en>*, **Facebook
<http://www.facebook.com/pages/discoverpcNET-Computer-Solutions-Center/35471145348>,
**LinkedIn
<https://www.linkedin.com/in/travus-elm-73842268?trk=nav_responsive_tab_profile>*

PRIVILEGED AND CONFIDENTIAL COMMUNICATION This e-mail transmission, and any
documents, files or previous e-mail messages attached to it, may contain
confidential information that is legally privileged. If you are not the
intended recipient or a person responsible for delivering it to the
intended recipient, you are hereby notified that any disclosure, copying,
distribution or use of any of the information contained in or attached to
this transmission is STRICTLY PROHIBITED. If you have received this
transmission in error, please: (1) immediately notify me by reply e-mail,
or by collect telephone call; and (2) destroy the original transmission and
its attachments without reading or saving in any manner
.

**Comment by nexusofdoom** [comment]
ok working on this

getting a error
   ./configure: error: the HTTP image filter module requires the GD library.


do I nee that ?


also this is what I am running with the

./configure --prefix=/usr/local/etc/nginx --with-cc-opt='-I
/usr/local/include' --with-ld-opt='-L /usr/local/lib'
--conf-path=/usr/local/etc/nginx/nginx.conf
--sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid
--error-log-path=/var/log/nginx/error.log --user=www --group=www
--modules-path=/usr/local/libexec/nginx --with-file-aio
--http-client-body-temp-path=/var/tmp/nginx/client_body_temp
--http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp
--http-proxy-temp-path=/var/tmp/nginx/proxy_temp
--http-scgi-temp-path=/var/tmp/nginx/scgi_temp
--http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp
--http-log-path=/var/log/nginx/access.log
--add-module=/usr/portbuild/www/nginx/work/ngx_cache_purge-2.3
--with-http_flv_module --with-http_geoip_module=dynamic
--with-http_gzip_static_module --with-http_image_filter_module=dynamic
--with-http_mp4_module
--add-module=/usr/portbuild/www/nginx/work/nginx-range-cache-0.2
--with-http_realip_module --with-http_slice_module
--with-http_stub_status_module --with-pcre --with-http_v2_module
--with-stream=dynamic --with-stream_ssl_module
--with-stream_ssl_preread_module --with-http_ssl_module

how I got to this point

mkdir /usr/portbuild/
mkdir /usr/portbuild/www/
mkdir /usr/portbuild/www/nginx/
mkdir  /usr/portbuild/www/nginx/work


cd /usr/portbuild/www/nginx/work


wget "
https://codeload.github.com/wandenberg/nginx-push-stream-module/tar.gz/0.5.1?dummy=/wandenberg-nginx-push-stream-module-0.5.1_GH0.tar.gz
"
tar zxvf
"0.5.1?dummy=%2Fwandenberg-nginx-push-stream-module-0.5.1_GH0.tar.gz"


wget "http://labs.frickle.com/files/ngx_cache_purge-2.3.tar.gz"
tar zxvf "ngx_cache_purge-2.3.tar.gz"


wget "
https://codeload.github.com/multiplay/nginx-range-cache/tar.gz/0.2?dummy=/multiplay-nginx-range-cache-0.2_GH0.tar.gz
"
tar zxvf "0.2?dummy=%2Fmultiplay-nginx-range-cache-0.2_GH0.tar.gz"



./configure
--add-module=/usr/portbuild/www/nginx/work/nginx-push-stream-module-0.5.1

./configure --add-module=/usr/portbuild/www/nginx/work/ngx_cache_purge-2.3

./configure --add-module=/usr/portbuild/www/nginx/work/nginx-range-cache-0.2







<http://www.discoverpc.net>
Travus Elm - Support Specialist
travus@discoverpc.net discoverpc.NET <http://discoverpc.net/>, 1402 Tower
Ave., Superior, WI 54880
Local: (715) 398-6767 ::: Toll-free: (800) 721-1350
Mobile: (218) 260-1940 ::: Fax: (866) 704-3660
*Follow or like us on **Google+*
<https://plus.google.com/111445774308955992766/about?gl=us&hl=en>*, **Facebook
<http://www.facebook.com/pages/discoverpcNET-Computer-Solutions-Center/35471145348>,
**LinkedIn
<https://www.linkedin.com/in/travus-elm-73842268?trk=nav_responsive_tab_profile>*

PRIVILEGED AND CONFIDENTIAL COMMUNICATION This e-mail transmission, and any
documents, files or previous e-mail messages attached to it, may contain
confidential information that is legally privileged. If you are not the
intended recipient or a person responsible for delivering it to the
intended recipient, you are hereby notified that any disclosure, copying,
distribution or use of any of the information contained in or attached to
this transmission is STRICTLY PROHIBITED. If you have received this
transmission in error, please: (1) immediately notify me by reply e-mail,
or by collect telephone call; and (2) destroy the original transmission and
its attachments without reading or saving in any manner
.

**Comment by nexusofdoom** [comment]
got most of it working have this issue when starting nginx

nginx: [alert] setsockopt(SO_ACCEPTFILTER, "httpready") for 10.0.4.53:80
failed, ignored (2: No such file or directory)

**Comment by nexusofdoom** [comment]
ok almost all done then onto more testing

pkg install GeoIP
/usr/local/bin/geoipupdate.sh
pkg install libgd

mkdir "/usr/portbuild/www/nginx/work"
mkdir "/data/www/cache/installs"
mkdir"/data/www/logs/"

cd /usr/portbuild/www/nginx/work

nano /boot/defaults/loader.conf
# add to end of file
accf_http_load = "YES"
wget "https://codeload.github.com/wandenberg/nginx-push-stream-module/tar.gz/0.5.1?dummy=/wandenberg-nginx-push-stream-module-0.5.1_GH0.tar.gz"

tar zxvf "0.5.1?dummy=%2Fwandenberg-nginx-push-stream-module-0.5.1_GH0.tar.gz"

wget "http://labs.frickle.com/files/ngx_cache_purge-2.3.tar.gz"

tar zxvf "ngx_cache_purge-2.3.tar.gz"

wget "https://codeload.github.com/multiplay/nginx-range-cache/tar.gz/0.2?dummy=/multiplay-nginx-range-cache-0.2_GH0.tar.gz"

tar zxvf "0.2?dummy=%2Fmultiplay-nginx-range-cache-0.2_GH0.tar.gz"

#./configure --add-module=/usr/portbuild/www/nginx/work/nginx-push-stream-module-0.5.1
#./configure --add-module=/usr/portbuild/www/nginx/work/ngx_cache_purge-2.3
#./configure --add-module=/usr/portbuild/www/nginx/work/nginx-range-cache-0.2

#./configure: error: the HTTP image filter module requires the GD library.

#wget "https://github.com/libgd/libgd/releases/download/gd-2.2.5/libgd-2.2.5.tar.gz"

#tar zxvf "gd-2.2.5/libgd-2.2.5.tar.gz"

#cd libgd-2.2.5

#./configure

#make

#make install

#or

#pkg install libgd

#cd to src nginx files location then run

./configure --prefix=/usr/local/etc/nginx --with-cc-opt='-I
/usr/local/include' --with-ld-opt='-L /usr/local/lib'
--conf-path=/usr/local/etc/nginx/nginx.conf
--sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid
--error-log-path=/var/log/nginx/error.log --user=www --group=www
--modules-path=/usr/local/libexec/nginx --with-file-aio
--http-client-body-temp-path=/var/tmp/nginx/client_body_temp
--http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp
--http-proxy-temp-path=/var/tmp/nginx/proxy_temp
--http-scgi-temp-path=/var/tmp/nginx/scgi_temp
--http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp
--http-log-path=/var/log/nginx/access.log
--add-module=/usr/portbuild/www/nginx/work/ngx_cache_purge-2.3
--with-http_flv_module --with-http_geoip_module=dynamic
--with-http_gzip_static_module --with-http_image_filter_module=dynamic
--with-http_mp4_module
--add-module=/usr/portbuild/www/nginx/work/nginx-range-cache-0.2
--with-http_realip_module --with-http_slice_module
--with-http_stub_status_module --with-pcre --with-http_v2_module
--with-stream=dynamic --with-stream_ssl_module
--with-stream_ssl_preread_module --with-http_ssl_module

make
make install

**Comment by stevenh** [comment]
Closing prior to archiving this repo
