### ISSUE TITLE
windows 10 downloads more then one time

### ISSUE THREAD

**Issue by nexusofdoom** [multiplay/lancache#13]
once the pc is done downloading the update nginx is still downloading files 
and it looks like it doing it 3 times 3 diff connections 

![image](https://user-images.githubusercontent.com/16519553/30522602-7c1f9a02-9b98-11e7-88aa-a6376b987152.png)

**Comment by nexusofdoom** [comment]
for the one update that should be about a 1gb it downloaded about 8gb of data

**Comment by nexusofdoom** [comment]
log file 
[lancache-microsoft-access.txt](https://github.com/multiplay/lancache/files/1309209/lancache-microsoft-access.txt)

**Comment by stevenh** [comment]
Closing prior to archiving this repo
