### ISSUE TITLE
Fortnite

### ISSUE THREAD

**Issue by ju2256** [multiplay/lancache#14]
Has anyone try to cache Fortnite from Epic Games ?

https://www.epicgames.com/fortnite/fr/buy-now/battle-royale

Thanks

**Comment by RyanEwen** [comment]
It looks like this games files are pulled in through HTTPS / SSL and thus won't easily be cacheable. I am trying to work on this for my own lan cacher (see my profile if interested). I don't think there's an easy solution, though.
