### ISSUE TITLE
Use nginx splice module?

### ISSUE THREAD

**Issue by jkroepke** [multiplay/lancache#4]
Hi,

nginx released a splice module in version 1.10.

It would be more awsome to use the splice module instead the range_cache module, because you can use pre compiled distro packages (ubuntu, fedora, ..).

Did you know, its possible to do this?

**Comment by liv3d** [comment]
Hey,

We looked at the nginx splice module for another project which uses a similar method, but the md5 hash of the file changes and in turn we couldn't then run the application.

We'd need to test this again though 😄

**Comment by stevenh** [comment]
Closing prior to archiving this repo
