### ISSUE TITLE
Riot CDN

### ISSUE THREAD

**Issue by ColbyAttack** [multiplay/lancache#5]
Having an issue with the Riot CDN, no longer able to cache anything and its pulling directly to the client without being cached server side. Any ideas?

**Comment by pyro2927** [comment]
What hosts are you using? I think you'll want to use `l3cdn.riotgames.com` and `worldwide.l3cdn.riotgames.com`.

**Comment by junkhacker** [comment]
they just released a new client, i wonder what changes came with it

**Comment by stevenh** [comment]
Any feedback on @pyro2927 suggestion @ColbyAttack ?

**Comment by stevenh** [comment]
Closing prior to archiving this repo
