### ISSUE TITLE
Range_cache module

### ISSUE THREAD

**Issue by ekhoury2000** [multiplay/lancache#6]
Hi @liv3d ,

sorry but this is not an issue just a question:

What do u mean by (range_cache module (unreleased watch this space))?

Is range_cache module something in nginx new versions? and u suggest pulling the image on my server using docker or just installing everything as shown in blog?

Thanks in advance

**Comment by liv3d** [comment]
Hey!

We don't currently have a docker image with range_cache in. 

I'll have a word internally and see if we can sort out a release at some time soon (even if it's just a docker container with it all in).

**Comment by b33tage** [comment]
Any luck with this module release?

**Comment by Kozlowlw** [comment]
Any updates? Really need to get Xbox One caching working (updating 40 consoles at a time is a pain)

**Comment by stevenh** [comment]
Thanks for the chase @ChainedHope here you go https://github.com/multiplay/nginx-range-cache
