### ISSUE TITLE
Need commercial version of nginx?

### ISSUE THREAD

**Issue by sprat** [multiplay/lancache#9]
I am using version 1.13.5 and I get the following warning and error:

```
2017/09/09 17:32:38 [emerg] 10#10: accept filters "accept_filter=httpready" are not supported on this platform, ignored in /etc/nginx/vhosts/lancache.conf:9
nginx: [emerg] accept filters "accept_filter=httpready" are not supported on this platform, ignored in /etc/nginx/vhosts/lancache.conf:9
2017/09/09 17:32:38 [emerg] 10#10: unknown directive "proxy_cache_purge" in /etc/nginx/lancache/proxy-cache:35
nginx: [emerg] unknown directive "proxy_cache_purge" in /etc/nginx/lancache/proxy-cache:35
```

As I understand it, I need a commercial version of nginx to run lancache, right? Or I missed something?

**Comment by stevenh** [comment]
Nope accept_filter is a FreeBSD only option just remove it from your config if your running something else.

**Comment by stevenh** [comment]
For the proxy_cache_purge you will need nginx compiled with ngx_http_proxy_module

**Comment by sprat** [comment]
Thanks for the answers. In fact, I had the http_proxy module but I was missing the http_cache_purge module from the distribution. Problem solved, thanks!
